# Generated by Django 3.2.12 on 2022-03-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120, unique=True)),
                ('colour', models.CharField(max_length=120, unique=True)),
                ('battery', models.PositiveIntegerField()),
                ('storage', models.PositiveIntegerField()),
                ('ram', models.PositiveIntegerField()),
                ('processor', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
